name: vertical_card_pager
description: Use dynamic and beautiful card view pagers to help you create great apps.
version: 1.5.0
homepage: https://github.com/Origogi/Vertical_Card_Pager

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

